name: Saucectl Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Saucectl
        run: |
          curl -L https://saucelabs.github.io/saucectl/install | bash
          echo "$HOME/.sauce/bin" >> $GITHUB_PATH

      - name: Run saucectl
        run: saucectl run