# https://docs.saucelabs.com/web-apps/automated-testing/cypress/
# https://docs.saucelabs.com/web-apps/automated-testing/cypress/yaml/v1/
apiVersion: v1
kind: cypress
sauce:
  region: eu-central-1 # or us-west-1
  # combined with the shard:concurrency setting
  concurrency: 75
  metadata:
    tags:
      - cypress
      - cross-browser
      - config-ex3
      - saucectl
      - github-action
    build: "config-ex3 $CURRENT_TIME"
cypress:
  version: package.json
  configFile: "cypress.config.js" # We determine related files based on the location of the config file.
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites:
  # Chrome
  - name: "Swag Labs Shard Tests Chrome"
    browser: "chrome"
    platformName: "Windows 10"
    screenResolution: "1400x1050"
    shard: spec
    config:
      specPattern: [ "cypress/e2e/**/login.*", cypress/e2e/**/swag.* ]
      excludeSpecPattern: [ "cypress/e2e/**/login.failed.cy.js" ]
  # Firefox
  - name: "Swag Labs Shard Tests Firefox"
    browser: "firefox"
    platformName: "Windows 10"
    screenResolution: "1400x1050"
    shard: spec
    config:
      specPattern: [ "cypress/e2e/**/login.*", cypress/e2e/**/swag.* ]
      excludeSpecPattern: [ "cypress/e2e/**/login.failed.cy.js" ]
  # MicrosoftEdge
  - name: "Swag Labs Shard Tests MicrosoftEdge"
    browser: "microsoftedge"
    platformName: "Windows 10"
    screenResolution: "1400x1050"
    shard: spec
    config:
      specPattern: [ "cypress/e2e/**/login.*", cypress/e2e/**/swag.* ]
      excludeSpecPattern: [ "cypress/e2e/**/login.failed.cy.js" ]
